<?php
return [
    'mainMenu'                  => 'Главное меню',
    'eventNotFount'             => 'На этот день нет события.',
    'schedule'                  => 'Расписание',
    'trainingGames'             => 'Тренировочные игры',
    'signUpForEvent'            => 'Пойду',
    'skipEvent'                 => 'Не пойду',
    'signUpForEventAnyway'      => 'Все же пойду',
    'skipEventAnyway'           => 'Все же не пойду',
    'descriptionIsEmpty'        => 'Описания еще нет.',
    'youAreSignedUp'            => 'Вы записаны на событие.',
    'youAreSkipped'             => 'Вы отписаны от события.',
    'setClubAdmins'             => 'Админы клубов',
    'selectClub'                => 'Сперва выберите клуб',
    'back'                      => '◀️ Назад',
    'cancel'                    => 'Отменить',
    'selectClubAdmins'          => 'Выберите администраторов клуба',
    'userIsAdminOfAnotherClub'  => 'Пользователь является администратором другого клуба.',
    'whoWillComeToEvent'        => 'Кто пойдет на событие?',
    'selectMonth'               => 'Выберите месяц',
    'selectDay'                 => 'Выберите день',
    'createEvent'               => 'Создать событие',
    'edit'                      => 'Редактировать',
    'delete'                    => 'Удалить',
    'successfullyDeleted'       => 'Событие удалено.',
    'writeDescription'          => 'Укажите описание события',
    'successfullyCreated'       => 'Событие создано',
    'editClub'                  => 'Редактировать клуб',
    'editClubTitle'             => '✏️ название',
    'editClubDescription'       => '✏️ описание',
    'editClubTrainingGames'     => '✏️ тренировочные игры',
    'writeNewValue'             => 'Напишите новое значение',
    'successfullyUpdated'       => 'Событие обновлено.',
];
